"""Generate source-of-truth README claim documents."""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from scripts.repo_facts import ROOT, RepoFacts, project_facts


EN_PATH = Path("docs/generated/claims.md")
KR_PATH = Path("docs/generated/claims_kr.md")


def _trap_rows(facts: RepoFacts) -> str:
    return "\n".join(f"| `{trap.id}` | {trap.hypothesis} |" for trap in facts.traps)


def _trap_bullets(facts: RepoFacts) -> str:
    return "\n".join(f"- `{trap.id}`: {trap.hypothesis}" for trap in facts.traps)


def build_claim_docs(facts: RepoFacts | None = None) -> dict[Path, str]:
    facts = facts or project_facts()
    english = f"""<!-- Generated by scripts/generate_readme_claims.py; do not edit by hand. -->
# Generated Source-of-Truth Claims

These claims are generated from local repository sources: `pyproject.toml`,
`src/mini_antemortem_cli/traps.py`, and `src/mini_antemortem_cli/cli.py`.

| Claim | Generated value |
|---|---|
| GitHub repository | `{facts.repository_name}` |
| PyPI distribution | `{facts.distribution_name}` |
| Install command | `{facts.install_command}` |
| Python import package | `{facts.import_package}` |
| Package version | `{facts.version}` |
| CLI command | `{facts.cli_command}` |
| CLI subcommands | `{', '.join(facts.cli_subcommands)}` |
| MCP extra | `{facts.mcp_extra}` |
| MCP entry point | `{facts.mcp_command}` |
| MCP module command | `{facts.mcp_module_command}` |
| Built-in trap count | `{facts.trap_count}` |

## Built-In Trap IDs

| Trap ID | Hypothesis |
|---|---|
{_trap_rows(facts)}

## Source-Backed Commands

| Purpose | Command |
|---|---|
| Deterministic tests | `python -m pytest -q` |
| Golden cases | `python scripts/run_golden_cases.py --check` |
| False-positive audit | `python scripts/run_false_positive_audit.py --check` |
| Repository self-check | `python scripts/check_repo_consistency.py` |
| Generated claims check | `python scripts/generate_readme_claims.py --check` |
| Fixture integrity | `python scripts/verify_fixture_integrity.py` |
| Deterministic demo replay | `python examples/demo_replay.py` |
| Wheel smoke install | `python scripts/wheel_smoke_install.py dist/*.whl` |
| Release audit | `python scripts/release_audit.py --no-network` |
"""
    korean = f"""<!-- Generated by scripts/generate_readme_claims.py; do not edit by hand. -->
# 생성된 소스 오브 트루스 claims

이 문서는 로컬 저장소의 `pyproject.toml`, `src/mini_antemortem_cli/traps.py`,
`src/mini_antemortem_cli/cli.py`에서 생성됩니다.

| Claim | 생성값 |
|---|---|
| GitHub repository | `{facts.repository_name}` |
| PyPI distribution | `{facts.distribution_name}` |
| Install command | `{facts.install_command}` |
| Python import package | `{facts.import_package}` |
| Package version | `{facts.version}` |
| CLI command | `{facts.cli_command}` |
| CLI subcommands | `{', '.join(facts.cli_subcommands)}` |
| MCP extra | `{facts.mcp_extra}` |
| MCP entry point | `{facts.mcp_command}` |
| MCP module command | `{facts.mcp_module_command}` |
| Built-in trap count | `{facts.trap_count}` |

## Built-In Trap IDs

{_trap_bullets(facts)}

## 검증 명령

| 목적 | 명령 |
|---|---|
| Deterministic tests | `python -m pytest -q` |
| Golden cases | `python scripts/run_golden_cases.py --check` |
| False-positive audit | `python scripts/run_false_positive_audit.py --check` |
| Repository self-check | `python scripts/check_repo_consistency.py` |
| Generated claims check | `python scripts/generate_readme_claims.py --check` |
| Fixture integrity | `python scripts/verify_fixture_integrity.py` |
| Deterministic demo replay | `python examples/demo_replay.py` |
| Wheel smoke install | `python scripts/wheel_smoke_install.py dist/*.whl` |
| Release audit | `python scripts/release_audit.py --no-network` |
"""
    return {EN_PATH: english, KR_PATH: korean}


def _check(root: Path, docs: dict[Path, str]) -> int:
    failures = 0
    for rel, expected in docs.items():
        path = root / rel
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual != expected:
            failures += 1
            print(f"STALE_GENERATED_DOC: {rel}", file=sys.stderr)
            diff = difflib.unified_diff(
                actual.splitlines(),
                expected.splitlines(),
                fromfile=str(rel),
                tofile=f"{rel} (expected)",
                lineterm="",
            )
            for line in list(diff)[:80]:
                print(line, file=sys.stderr)
    return 1 if failures else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated docs are stale.")
    args = parser.parse_args(argv)

    docs = build_claim_docs()
    if args.check:
        return _check(ROOT, docs)

    for rel, content in docs.items():
        path = ROOT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
